### ISSUE TITLE
Error al editar artículos en el carrito

### ISSUE THREAD

**Issue by Miguelslo27** [Miguelslo27/ecommerce-php-reborn#105]
Si se edita la cantidad de un artículo en el carrito, y se pone números negativos, se descuenta del total, el precio del artículo multiplicado por la cantidad igual y opuesta al número negativo, con lo que se estaría perdiendo dinero en dicha orden

**Comment by fdsosa** [comment]
Buenas, llegué a una solución pero no sé si es la mas práctica.

Colocar 'this.style.pointerEvents="none";' en la función 'handleUpdate' de 'cart.js'.
Lo testié y aparentemente funciona bien.
Desconocía esta propiedad css, busqué si era una mala practica o algo por el estilo pero no encontré mucho. Que te parece a vos?
