### ISSUE TITLE
Convertir los componentes en MVC

### ISSUE THREAD

**Issue by Miguelslo27** [Miguelslo27/ecommerce-php-reborn#67]
Las páginas deberían de incluir el componente completo, mientras que el componente debería ser parte del template y tener un controlador que maneja el model (M y C) (el archivo que implementa `newDocument`) y la vista (V) con sus respectivos estilos y comportamientos de UI (HTML, CSS y JS)

Componentizar las páginas básicas en el orden de prioridad a continuación

### Primero:
- [x] Home
- [x] Categorías
- [x] Detalle de Categoría
- [x] Articulos
- [x] Registro
- [x] Login
  - [x] Enviar a la home si ya está loggeado
  - [x] Logout
- [x] Carrito
  - [x] Carrito vacío
  - [x] Agregar al carrito
  - [x] Carrito completo
  - [x] Actualizar artículos en el carrito
  - [x] Eliminar artículos del carrito
- [x] Resumen
- [x] Pagar
  - [x] Formulario de Datos de Facturzación
  - [x] Formulario de Datos de Envío
  - [x] Formulario de Método de Pago
    * ~Integrar MercadoPago (Prueba de Concepto)~
- [x] 404
- [x] Contacto

### Luego:
- [x] Cuenta
- [x] Detalle de Articulo
- [x] Resultado de Búsqueda
- [x] Recuperar contraseña

**Comment by Martin021** [comment]
" agregar al carrito" después de agregar un item lo agrega nuevamente al seleccionar Home.

**Comment by Martin021** [comment]
"carrito vacio" quedó tan bien que cuando agregas algo,  Sigue vacío persistente el atorrante

**Comment by Martin021** [comment]
"registro" 

- no admite caracteres especiales.  Cómo tildes o diéresis. Para que obligar a la gente escribir mal su nombre, apellido, departamento o localidad Je
- un mail de bienvenido post registro no viene mal

**Comment by Miguelslo27** [comment]
Voy a registrar los bugs como tickets, gracias por el feedback 😄 
El de Carrito Vacío es lógico porque estoy trabajando en el resumen, todavía no está finalizado, hasta que no lo tenga pronto no lo mando a demo
